export const petsData = [
  {
    id: '1',
    name: 'Zelda',
    age: 2,
    breed: 'Labrador',
    size: 'Médio',
    location: 'Brasil, São Paulo - SP',
    image: '/assets/images/zelda.jpg',
    description: 'Sempre pronta para aventuras, corajosa',
  },
  {
    id: '2',
    name: 'Thor',
    age: 4,
    breed: 'Pastor Alemão',
    size: 'Grande',
    location: 'Brasil, Curitiba - PR',
    image: '/assets/images/thor.jpg',
    description: 'Protetor, forte e inteligente.',
  },
  {
    id: '3',
    name: 'Mimi',
    age: 1,
    breed: 'Persa',
    size: 'Pequeno',
    location: 'Brasil, Belo Horizonte - MG',
    image: '/assets/images/mimi.jpg',
    description: 'Gatinha calma e amorosa.',
  },
  {
    id: '4',
    name: 'Morty',
    age: 12,
    breed: 'orelha-vermelha',
    size: 'Médio',
    location: 'Brasil, Manaus, Amazonas',
    image: '/assets/images/morty.jpg',
    description: 'Atrapalhado e carismático',
  },
  {
    id: '5',
    name: 'Sonic',
    age: 1,
    breed: 'Abíssimo',
    size: 'Pequeno',
    location: 'Recife - PE',
    image: '/assets/images/sonic.jpg',
    description: 'Elétrico e cheio de energia',
  },
  {
    id: '6',
    name: 'Groot',
    age: 2,
    breed: 'Sírio (Hamster)',
    size: 'Pequeno',
    location: 'Brasília - DF',
    image: '/assets/images/groot.jpg',
    description: 'Simples, adorável. Repete a rotina com graça',
  },
  {
    id: '7',
    name: 'Coraline',
    age: 2,
    breed: 'Siamês',
    size: 'Médio',
    location: 'Campinas - SP',
    image: '/assets/images/coraline.jpg',
    description: 'Corajosa e curiosa. Personalidade forte',
  },
  {
    id: '8',
    name: 'Stitch',
    age: 5,
    breed: 'Pug',
    size: 'Pequeno',
    location: 'São Paulo - SP',
    image: '/assets/images/stitch.jpg',
    description: 'Dorminhoco, leal e família',
  },
  {
    id: '9',
    name: 'Simba',
    age: 2,
    breed: 'Angorá Turco',
    size: 'Médio',
    location: 'Rio de Janeiro - RJ',
    image: '/assets/images/simba.jpg',
    description: 'Curioso, amigável. Exige atenção exclusiva',
  },
  {
    id: '10',
    name: 'Morfeu',
    age: 2,
    breed: 'Azul Russo',
    size: 'Médio',
    location: 'Joinville - SC',
    image: '/assets/images/morfeu.jpg',
    description: 'Silencioso, elegante',
  },
  {
    id: '11',
    name: 'Engraxate',
    age: 2,
    breed: 'Beagle',
    size: 'Médio',
    location: 'Natal - RN',
    image: '/assets/images/engraxate.jpg',
    description: 'Aventureiro e com faro apurado',
  },
  {
    id: '12',
    name: 'Cheshire',
    age: 2,
    breed: 'Ragdoll',
    size: 'Grande',
    location: 'Porto Alegre - RS',
    image: '/assets/images/cheshire.jpg',
    description: 'Olhar enigmático e sorriso imaginário',
  },
  {
    id: '13',
    name: 'Loki',
    age: 2,
    breed: 'Border Collie',
    size: 'Médio',
    location: 'São Luís - MA',
    image: '/assets/images/loki.jpg',
    description: 'Astuto e travesso, precisa de atividade mental',
  },
  {
    id: '14',
    name: 'Gollum',
    age: 4,
    breed: 'Sphynx',
    size: 'Pequeno',
    location: 'Niterói - RJ',
    image: '/assets/images/gollum.jpg',
    description: 'Único. Sensível ao frio, ama cobertas e mimos',
  },
  {
    id: '15',
    name: 'Yoda',
    age: 8,
    breed: 'Tigre dágua',
    size: 'Médio',
    location: 'Campinas - SP',
    image: '/assets/images/yoda.jpg',
    description: 'Calmo, sábio e muito observador',
  },

];